/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blood;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class UpgradeUsers extends javax.swing.JFrame {

    public int z=0;
    public UpgradeUsers() {
        initComponents();
        EmailShow.setVisible(false);
        PassShow.setVisible(false);
        panelShow.setVisible(false);
        btnSave.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtSearchEmail = new javax.swing.JTextField();
        txtNPass = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtCupass = new javax.swing.JTextField();
        ErrorPass = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtCPass = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        panelShow = new javax.swing.JPanel();
        PassShow = new javax.swing.JTextField();
        EmailShow = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(620, 285));
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(22, 22, 22));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(36, 36, 36));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        jPanel3.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel3.setMinimumSize(new java.awt.Dimension(319, 183));
        jPanel3.setPreferredSize(new java.awt.Dimension(325, 189));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearchEmail.setBackground(new java.awt.Color(36, 36, 36));
        txtSearchEmail.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtSearchEmail.setForeground(new java.awt.Color(204, 204, 255));
        txtSearchEmail.setBorder(null);
        txtSearchEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchEmailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchEmailKeyTyped(evt);
            }
        });
        jPanel3.add(txtSearchEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 200, 40));

        txtNPass.setBackground(new java.awt.Color(36, 36, 36));
        txtNPass.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtNPass.setForeground(new java.awt.Color(204, 204, 255));
        txtNPass.setText("New Password");
        txtNPass.setBorder(null);
        txtNPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNPassFocusLost(evt);
            }
        });
        txtNPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNPassKeyReleased(evt);
            }
        });
        jPanel3.add(txtNPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 190, 40));

        btnSave.setBackground(new java.awt.Color(36, 36, 36));
        btnSave.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(204, 204, 255));
        btnSave.setText("Save");
        btnSave.setBorder(null);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel3.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 200, 40));

        txtCupass.setBackground(new java.awt.Color(36, 36, 36));
        txtCupass.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtCupass.setForeground(new java.awt.Color(204, 204, 255));
        txtCupass.setText("Current Password");
        txtCupass.setBorder(null);
        txtCupass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCupassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCupassFocusLost(evt);
            }
        });
        jPanel3.add(txtCupass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 190, 40));

        ErrorPass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ErrorPass.setForeground(new java.awt.Color(0, 255, 204));
        ErrorPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(ErrorPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 280, 29));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 200, 10));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 200, 10));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 200, 10));

        txtCPass.setBackground(new java.awt.Color(36, 36, 36));
        txtCPass.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtCPass.setForeground(new java.awt.Color(204, 204, 255));
        txtCPass.setText("Confirm Password");
        txtCPass.setBorder(null);
        txtCPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCPassFocusLost(evt);
            }
        });
        txtCPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCPassKeyReleased(evt);
            }
        });
        jPanel3.add(txtCPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 190, 40));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 200, 10));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("E-mail");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 70, 30));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, -1));

        jButton1.setBackground(new java.awt.Color(36, 36, 36));
        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jButton1.setText("Close");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 490, 80, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 419));

        panelShow.setBackground(new java.awt.Color(22, 22, 22));
        panelShow.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        PassShow.setBackground(new java.awt.Color(22, 22, 22));
        PassShow.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        PassShow.setForeground(new java.awt.Color(204, 204, 255));
        PassShow.setBorder(null);
        PassShow.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PassShowComponentShown(evt);
            }
        });

        EmailShow.setBackground(new java.awt.Color(22, 22, 22));
        EmailShow.setFont(new java.awt.Font("Comic Sans MS", 0, 15)); // NOI18N
        EmailShow.setForeground(new java.awt.Color(204, 204, 255));
        EmailShow.setBorder(null);
        EmailShow.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                EmailShowComponentShown(evt);
            }
        });

        javax.swing.GroupLayout panelShowLayout = new javax.swing.GroupLayout(panelShow);
        panelShow.setLayout(panelShowLayout);
        panelShowLayout.setHorizontalGroup(
            panelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(EmailShow, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator7)
                    .addComponent(PassShow, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panelShowLayout.setVerticalGroup(
            panelShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShowLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(EmailShow, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(PassShow, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel1.add(panelShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 230, 220));

        jButton2.setBackground(new java.awt.Color(36, 36, 36));
        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 255));
        jButton2.setText("Close");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       
      
        String searchpass= txtSearchEmail.getText();
        String newPass = txtNPass.getText();
        panelShow.setVisible(false);
        EmailShow.setVisible(false);
        PassShow.setVisible(false);
        String newcpass= txtCPass.getText();
        if(newPass.equals(newcpass))
        {
            try {

                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/blood", "root", "***###botki143JN");
                Statement st = (Statement) con.createStatement();
                String query = "update reg set Pass='" + newPass + "' where Pass='" + searchpass + "'";
                st.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "Updated");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Sorry! Password doesn't match");
        }
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtSearchEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchEmailKeyReleased
       
        String emailsearch=txtSearchEmail.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/blood", "root", "***###botki143JN");
            Statement st = (Statement)con.createStatement();
            String query = "select *from reg1 where Email='"+emailsearch+"'";
            ResultSet rs = st.executeQuery(query);
            if(rs.next())
            {
                ErrorPass.setText("complete");
                
                EmailShow.setText(rs.getString(1));
                PassShow.setText(rs.getString(2));
                if(z==0)
                {
                    try {
                        Thread.sleep(100);
                        panelShow.setVisible(true);
                        EmailShow.setVisible(true);
                        PassShow.setVisible(true);
                        EmailShow.setEditable(false);
                        PassShow.setEditable(false);
                        txtSearchEmail.setEditable(false);
                        ErrorPass.setText(null);
                    } catch (Exception e) {
                    }
                }
               
                txtCupass.setText(rs.getString(2));
                txtNPass.setEditable(true);
                txtCPass.setEditable(true);
                 btnSave.setVisible(true);
                
                
                
              
            }
            else
            {
                 ErrorPass.setText("Sorry! Email doesn't match");
            }
            
        } catch (Exception e) {
        }
            
    }//GEN-LAST:event_txtSearchEmailKeyReleased

    private void txtSearchEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchEmailKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSearchEmailKeyTyped

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        txtSearchEmail.setEditable(true);
        txtCupass.setEditable(false);
        txtNPass.setEditable(false);
        txtCPass.setEditable(false);
    }//GEN-LAST:event_formComponentShown

    private void EmailShowComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_EmailShowComponentShown
        
      
       
    }//GEN-LAST:event_EmailShowComponentShown

    private void PassShowComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PassShowComponentShown
       
    }//GEN-LAST:event_PassShowComponentShown

    private void txtCupassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCupassFocusGained
        
        if(txtCupass.getText().equals("Current Password"))
        {
            txtCupass.setText("");
            txtCupass.setForeground(new Color(204,204,255));
            
        } 
    }//GEN-LAST:event_txtCupassFocusGained

    private void txtCupassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCupassFocusLost
        
        if(txtCupass.getText().equals(""))
        {
            txtCupass.setText("Current Password");
            txtCupass.setForeground(new Color(204,204,255));
            
        } 
    }//GEN-LAST:event_txtCupassFocusLost

    private void txtNPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNPassFocusGained
        
       if(txtNPass.getText().equals("New Password"))
        {
            txtNPass.setText("");
            txtNPass.setForeground(new Color(204,204,255));
            
        } 
        
    }//GEN-LAST:event_txtNPassFocusGained

    private void txtNPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNPassFocusLost
        
        if(txtNPass.getText().equals(""))
        {
            txtNPass.setText("New Password");
            txtNPass.setForeground(new Color(204,204,255));
            
        } 
    }//GEN-LAST:event_txtNPassFocusLost

    private void txtCPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPassFocusGained
       
        if(txtCPass.getText().equals("Confirm Password"))
        {
            txtCPass.setText("");
            txtCPass.setForeground(new Color(204,204,255));
            
        } 
    }//GEN-LAST:event_txtCPassFocusGained

    private void txtCPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPassFocusLost
       
        if(txtCPass.getText().equals(""))
        {
            txtCPass.setText("Confirm Password");
            txtCPass.setForeground(new Color(204,204,255));
            
        } 
    }//GEN-LAST:event_txtCPassFocusLost

    private void txtNPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNPassKeyReleased
       
        String PATTERN = //"^[!,@,#,$,%,^,&,*,-,+A-Za-z0-9]{8,30}$";
                "^(?=.*[0-9])"
                       + "(?=.*[a-z])(?=.*[A-Z])"
                       + "(?=.*[@#$%^&*+=])"
                       + "(?=\\S+$).{8,20}$"; 
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtNPass.getText());
        if(!match.matches())
        {
            ErrorPass.setText("Uppercase/Lowercase/Numbers/Symbol");
        }
        else if(match.matches())
        {
            ErrorPass.setText("complete");
        }
        else
        {
            ErrorPass.setText(null);
        }
    }//GEN-LAST:event_txtNPassKeyReleased

    private void txtCPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPassKeyReleased
       
        String PATTERN = //"^[!,@,#,$,%,^,&,*,-,+A-Za-z0-9]{8,30}$";
                "^(?=.*[0-9])"
                       + "(?=.*[a-z])(?=.*[A-Z])"
                       + "(?=.*[@#$%^&*+=])"
                       + "(?=\\S+$).{8,20}$"; 
        Pattern patt = Pattern.compile(PATTERN);
        Matcher match = patt.matcher(txtCPass.getText());
        if(!match.matches())
        {
            ErrorPass.setText("Uppercase/Lowercase/Numbers/Symbol");
        }
        else if(match.matches())
        {
            ErrorPass.setText("complete");
        }
        else
        {
            ErrorPass.setText(null);
        }
    }//GEN-LAST:event_txtCPassKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpgradeUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpgradeUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpgradeUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpgradeUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpgradeUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailShow;
    private javax.swing.JLabel ErrorPass;
    private javax.swing.JTextField PassShow;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel panelShow;
    private javax.swing.JTextField txtCPass;
    private javax.swing.JTextField txtCupass;
    private javax.swing.JTextField txtNPass;
    private javax.swing.JTextField txtSearchEmail;
    // End of variables declaration//GEN-END:variables
}
